# **IMPORTATION DES LIBRAIRIES **

In [205]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import git as g

# **IMPORTATION DE LA BASE DE DONNEES **

In [2]:
# Code pour se connecter à github

repo= 'https://github.com/HPsurvey/Hello_pulse_sondage.git'
!git clone {repo}

Cloning into 'Hello_pulse_sondage'...
remote: Enumerating objects: 35, done.
remote: Counting objects: 100% (35/35), done.
remote: Compressing objects: 100% (22/22), done.
remote: Total 35 (delta 6), reused 27 (delta 4), pack-reused 0 (from 0)
Receiving objects: 100% (35/35), 219.07 KiB | 7.07 MiB/s, done.
Resolving deltas: 100% (6/6), done.

In [331]:
df = pd.read_csv('Hello_pulse_sondage/data/raw/survey.csv')
display(df)

,Horodateur,Connaissez-vous le terme « brainstorming » ?,Travaillez-vous plus souvent individuellement ou en groupe ?,Avez vous déjà utilisé une application de brainstorming ?,Miro,MindMeister,XMind,Klaxoon,Lucidchart / Lucidspark,Coggle,...,Une synchronisation avec d’autres outils comme Google drive…,Un système de rappel ou suivi des idées non développées,Un mode hors ligne ou application mobile utilisable partout,Une haute sécurité / confidentialité des données,Une option de brainstorm “anonyme” pour libérer la parole,Un/e assistant/e vocal ou dictée pour les idées à l’oral,Combien seriez-vous prêt(e) à payer pour accéder à des fonctionnalités avancées ?.1,Sur quels réseaux sociaux êtes vous le plus actif ?,Vous êtes :.1,Quel âge avez-vous ? .1
0,2025/06/25 4:53:36 PM UTC+3,3,En groupe,Non,NaN,NaN,NaN,NaN,NaN,NaN,...,3.0,4.0,4.0,5.0,3.0,4.0,4€,Instagram,Etudiant,18-25
1,2025/06/25 5:27:34 PM UTC+3,5,En groupe,Non,NaN,NaN,NaN,NaN,NaN,NaN,...,5.0,4.0,5.0,5.0,5.0,1.0,jusqu’à 15€,Instagram;Snapchat;TikTok;YouTube,Etudiant,18-25
2,2025/06/25 5:28:18 PM UTC+3,4,En groupe,Oui et j’utilise aussi les outils de brainstor...,2.0,1.0,1.0,NaN,1.0,1.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,2025/06/25 5:56:39 PM UTC+3,2,En groupe,Non,NaN,NaN,NaN,NaN,NaN,NaN,...,5.0,5.0,4.0,5.0,5.0,5.0,30,Instagram;Snapchat;TikTok;LinkedIn,Etudiant,18-25
4,2025/06/25 6:06:52 PM UTC+3,5,En groupe,Oui,1.0,1.0,2.0,NaN,1.0,1.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
243,2025/06/30 2:06:05 PM UTC+3,5,En groupe,Non,NaN,NaN,NaN,NaN,NaN,NaN,...,5.0,5.0,5.0,5.0,3.0,3.0,500€,LinkedIn,Cadre et profession intellectuelle supérieure,36-40
244,2025/06/30 4:55:26 PM UTC+3,5,En groupe,Oui et j’utilise aussi les outils de brainstor...,5.0,1.0,2.0,5.0,1.0,1.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
245,2025/07/01 4:08:46 PM UTC+3,5,En groupe,Oui et j’utilise aussi les outils de brainstor...,1.0,1.0,1.0,3.0,1.0,1.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
246,2025/07/02 1:53:35 PM UTC+3,5,En groupe,Oui et j’utilise aussi les outils de brainstor...,1.0,1.0,1.0,1.0,1.0,1.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
247,2025/07/08 12:52:28 PM UTC+3,5,Individuellement,Non,NaN,NaN,NaN,NaN,NaN,NaN,...,3.0,2.0,5.0,5.0,1.0,1.0,7 euros/mois,Instagram;LinkedIn;YouTube;WhatsApp,Etudiant,31-35

In [332]:
df.columns

Index(['Horodateur', 'Connaissez-vous le terme « brainstorming » ? ',
       'Travaillez-vous plus souvent individuellement ou en groupe ? ',
       'Avez vous déjà utilisé une application de brainstorming ?', 'Miro ',
       'MindMeister', 'XMind', 'Klaxoon', 'Lucidchart / Lucidspark', 'Coggle',
       'Microsoft Whiteboard', 'Zoom', 'Trello', 'Notion', 'Figma (et FigJam)',
       'Canva',
       'À quelle fréquence utilisez-vous l’intelligence artificielle ',
       'Quel degré de confiance accordez-vous initialement à l’intelligence artificielle pour produire des idées pertinentes et créatives ?',
       'Seriez-vous intéressé(e) par une nouvelle application de brainstorming avec une lA',
       'l’ergonomie ', ' l’accessibilité ',
       ' la fonctionnalité intelligente limitée', 'l’intégration des données ',
       ' la limitation des versions gratuites', 'confidentialité et sécurité',
       'un mode hors ligne ou application mobile utilisable partout',
       'un export facile en PDF, PNG, Word ou Trello/Notion',
       'Police de lecture adaptée à la dyslexie',
       'Correcteur orthographique bienveillant (pour personnes en situation de dysorthographie).',
       'Combien seriez-vous prêt(e) à payer pour accéder à des fonctionnalités avancées ?',
       'Sur quels réseaux sociaux êtes-vous le plus actif ? ', 'Vous êtes :',
       'Quel âge avez-vous ? ', 'Slack ', 'Microsoft teams ',
       'Figma (et FigJam).1', 'Klaxoon.1', 'Canva.1', 'XMind.1',
       'MindMeister.1', ' Microsoft Whiteboard', ' Zoom',
       'Google chat / google meet ', 'Trello ', 'Notion ',
       'À quelle fréquence utilisez-vous l’intelligence artificielle (IA) au quotidien ?',
       'Quel degré de confiance accordez-vous initialement à l’intelligence artificielle pour produire des idées pertinentes et créatives ?.1',
       'À quel niveau seriez-vous intéressé(e) par une nouvelle application de brainstorming avec une lA qui génère des idées en fonction d'un thème ?',
       'Une interface simple, fluide et intuitive',
       'Police de lecture adaptée à la dyslexie.1',
       'Correcteur orthographique bienveillant (pour personnes en situation de dysorthographie)',
       'Un mode collaboratif en temps réel',
       'Une fonction de génération d’idées par intelligence artificielle',
       'Des post-it ou cartes visuelles personnalisables',
       'Une organisation claire des idées : catégories, couleurs, hiérarchies',
       'Une possibilité de commentaires, votes ou réactions sur les idées partagées',
       'Des modèles prédéfinis de brainstorming',
       'Une possibilité d’intégrer des images, fichiers ou liens web',
       'Un export facile en PDF, PNG, Word ou Trello/Notion',
       'Une synchronisation avec d’autres outils comme Google drive…',
       'Un système de rappel ou suivi des idées non développées',
       'Un mode hors ligne ou application mobile utilisable partout',
       'Une haute sécurité / confidentialité des données',
       'Une option de brainstorm “anonyme” pour libérer la parole',
       'Un/e assistant/e vocal ou dictée pour les idées à l’oral',
       'Combien seriez-vous prêt(e) à payer pour accéder à des fonctionnalités avancées ?.1',
       'Sur quels réseaux sociaux êtes vous le plus actif ? ', 'Vous êtes :.1',
       'Quel âge avez-vous ? .1'],
      dtype='object')

In [333]:
df.shape

(248, 69)

In [334]:

#RENOMMER LES VARIABLES POUR LEQUELS LES INTERROGEES CONNAISSENT LE BRAINSTORMING (80)
df= df.rename(columns={'Connaissez-vous le terme « brainstorming » ? ':'def_brainstorming', 'Travaillez-vous plus souvent individuellement ou en groupe ? ':'hbt_travail',
        'Avez vous déjà utilisé une application de brainstorming ?': 'uti_appli_brainstorming',
        'Lucidchart / Lucidspark': 'Lucidchart_lucidpark',
       'Microsoft Whiteboard':'Microsoft_whiteboard', 'Figma (et FigJam)':'Figma_figjam',
       "À quelle fréquence utilisez-vous l’intelligence artificielle ": 'frequence_IA_O_brainsto',
       'Quel degré de confiance accordez-vous initialement à l’intelligence artificielle pour produire des idées pertinentes et créatives ?': 'confiance_IA_brainst',
       'Seriez-vous intéressé(e) par une nouvelle application de brainstorming avec une lA': 'interet_appli_brainst_IA',
       "l’ergonomie ":'ergonomie',  ' l’accessibilité ': 'accessibilite_O', ' la fonctionnalité intelligente limitée':'lim_fonctionalite_intelligente',
       'l’intégration des données ':'import_doc_O', ' la limitation des versions gratuites':'version_gratuite_lim_O',
       'confidentialité et sécurité':'secu_donnee_O',
       'un mode hors ligne ou application mobile utilisable partout':'outline_O',
       'un export facile en PDF, PNG, Word ou Trello/Notion': 'export_doc_O',
       'Police de lecture adaptée à la dyslexie': 'dyslexie_O',
        'Correcteur orthographique bienveillant (pour personnes en situation de dysorthographie).': 'correc_orto_bienveillant_O',
       'Combien seriez-vous prêt(e) à payer pour accéder à des fonctionnalités avancées ?': 'prix_fonctionnalite_av_O',
       'Sur quels réseaux sociaux êtes-vous le plus actif ? ':'act_social_media_O', 'Vous êtes :':'genre_O',
       'Quel âge avez-vous ? ':'age_O'})

In [335]:
#RENOMMER LES VARIABLES POUR LEQUELS LES INTERRONGEES NE CONNAISSENT PAS LE BRAINSTORMING (168)
df= df.rename(columns={'Slack ':'Slack_N', 'Microsoft teams ':'Microsoft_teams_N',
       'Figma (et FigJam).1':'Figma_figjam_N', 'Klaxoon.1':'Klaxoon_N', 'Canva.1':'Canva_N', 'XMind.1':'XMind_N',
       'MindMeister.1':'MindMeister_N','Google chat / google meet ': 'google_chat_meet_N', 'Trello ':'Trello_N',
       "À quelle fréquence utilisez-vous l’intelligence artificielle (IA) au quotidien ?":'frequence_IA_N_brainsto',
       'Quel degré de confiance accordez-vous initialement à l’intelligence artificielle pour produire des idées pertinentes et créatives ?.1': 'confiance_IA_brainst_N',
       "À quel niveau seriez-vous intéressé(e) par une nouvelle application de brainstorming avec une lA qui génère des idées en fonction d'un thème ?":'interet_appli_brainst_IA_N',
       'Une interface simple, fluide et intuitive':'UX_UI',
       'Police de lecture adaptée à la dyslexie.1':'dyslexie_N',

       'Correcteur orthographique bienveillant (pour personnes en situation de dysorthographie)': 'correc_orto_bienveillant_N',
       'Un mode collaboratif en temps réel':'collab_IRL_N',
       'Une fonction de génération d’idées par intelligence artificielle':'IA_generation_N',
       'Des post-it ou cartes visuelles personnalisables':'personalisation_visuel_N',
       'Une organisation claire des idées : catégories, couleurs, hiérarchies': 'org_idee_claire_N',
       'Une possibilité de commentaires, votes ou réactions sur les idées partagées':'social_media',
       'Des modèles prédéfinis de brainstorming':'templates_N',
       'Une possibilité d’intégrer des images, fichiers ou liens web':'import_doc_N',
       'Un export facile en PDF, PNG, Word ou Trello/Notion': 'export_doc_N',
       'Une synchronisation avec d’autres outils comme Google drive…':'synchronisation_outil_N',
       'Un système de rappel ou suivi des idées non développées':'task_tracking_N',
       'Un mode hors ligne ou application mobile utilisable partout':'outline_N',
       'Une haute sécurité / confidentialité des données':'secu_donnee_N',
       'Une option de brainstorm “anonyme” pour libérer la parole':'anonymat_N',
       'Un/e assistant/e vocal ou dictée pour les idées à l’oral':'assistant_vocal_N',
       'Combien seriez-vous prêt(e) à payer pour accéder à des fonctionnalités avancées ?.1':'prix_fonctionnalite_av_N',
       'Sur quels réseaux sociaux êtes vous le plus actif ? ':'act_social_media_N', 'Vous êtes :.1':'genre_N',
       'Quel âge avez-vous ? .1':'age_N'})

In [336]:
#Renommer la variable zoom situé dans  la colonne 41  en zoom_N et la variable zoom situé dans la colonne 11 en zoom_0 en fonction de leurs localisation

# Indentifier et renommer les index
col_index_zoom_N = 40
col_index_zoom_0 = 10

current_columns = df.columns.tolist()


#renommer les variables en fonction de leurs localisation
if col_index_zoom_N < len(current_columns):
    current_columns[col_index_zoom_N] = 'zoom_N'

if col_index_zoom_0 < len(current_columns):
    current_columns[col_index_zoom_0] = 'zoom_0'


#Assignation des modifications dans la base de données df
df.columns = current_columns

In [337]:
# Renommer la variable Notion situé dans la colonne 13 en Notion_O et la variable Notion situé dans la colonne 44 en Notion_N

# Identify the columns to rename by their index
col_index_notion_O = 12
col_index_notion_N = 43

current_columns = df.columns.tolist()

#renommer les variables en fonction de leurs localisation
if col_index_notion_O < len(current_columns):
    current_columns[col_index_notion_O] = 'Notion_O'

if col_index_notion_N < len(current_columns):
    current_columns[col_index_notion_N] = 'Notion_N'

#Assignation des modifications dans la base de données df
df.columns = current_columns

In [338]:
#suppression de la colonne horodateur

df = df.drop(columns=['Horodateur'])

In [273]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 248 entries, 0 to 247
Data columns (total 68 columns):
 #   Column                          Non-Null Count  Dtype
---  ------                          --------------  -----
 0   def_brainstorming               248 non-null    int64
 1   hbt_travail                     248 non-null    object
 2   uti_appli_brainstorming         248 non-null    object
 3   Miro                            80 non-null     float64
 4   MindMeister                     80 non-null     float64
 5   XMind                           80 non-null     float64
 6   Klaxoon                         48 non-null     float64
 7   Lucidchart_lucidpark            80 non-null     float64
 8   Coggle                          80 non-null     float64
 9   zoom_0                          80 non-null     float64
 10  Zoom                            80 non-null     float64
 11  Notion_O                        80 non-null     float64
 12  Notion                          80 non-null     float64
 13  Figma_figjam                    80 non-null     float64
 14  Canva                           80 non-null     float64
 15  frequence_IA_O_brainsto         80 non-null     float64
 16  confiance_IA_brainst            48 non-null     float64
 17  interet_appli_brainst_IA        80 non-null     float64
 18  ergonomie                       80 non-null     float64
 19  accessibilite_O                 80 non-null     float64
 20  lim_fonctionalite_intelligente  80 non-null     float64
 21  import_doc_O                    80 non-null     float64
 22  version_gratuite_lim_O          80 non-null     float64
 23  secu_donnee_O                   80 non-null     float64
 24  outline_O                       80 non-null     float64
 25  export_doc_O                    80 non-null     float64
 26  dyslexie_O                      49 non-null     float64
 27  correc_orto_bienveillant_O      49 non-null     float64
 28  prix_fonctionnalite_av_O        80 non-null     object
 29  act_social_media_O              80 non-null     object
 30  genre_O                         80 non-null     object
 31  age_O                           80 non-null     object
 32  Slack_N                         168 non-null    float64
 33  Microsoft_teams_N               168 non-null    float64
 34  Figma_figjam_N                  168 non-null    float64
 35  Klaxoon_N                       102 non-null    float64
 36  Canva_N                         168 non-null    float64
 37  XMind_N                         168 non-null    float64
 38  MindMeister_N                   168 non-null    float64
 39  zoom_N                          168 non-null    float64
 40   Zoom                           168 non-null    float64
 41  google_chat_meet_N              168 non-null    float64
 42  Notion_N                        168 non-null    float64
 43  Notion                          168 non-null    float64
 44  frequence_IA_N_brainsto         168 non-null    float64
 45  confiance_IA_brainst_N          101 non-null    float64
 46  interet_appli_brainst_IA_N      168 non-null    float64
 47  UX_UI                           168 non-null    float64
 48  dyslexie_N                      102 non-null    float64
 49  correc_orto_bienveillant_N      102 non-null    float64
 50  collab_IRL_N                    168 non-null    float64
 51  IA_generation_N                 168 non-null    float64
 52  personalisation_visuel_N        168 non-null    float64
 53  org_idee_claire_N               168 non-null    float64
 54  social_media                    168 non-null    float64
 55  templates_N                     168 non-null    float64
 56  import_doc_N                    168 non-null    float64
 57  export_doc_N                    168 non-null    float64
 58  synchronisation_outil_N         168 non-null    float64
 59  task_tracking_N                 168 non-null    float64
 60  outline_N                       168 non-null    float64
 61  secu_donnee_N                   168 non-null    float64
 62  anonymat_N                      168 non-null    float64
 63  assistant_vocal_N               168 non-null    float64
 64  prix_fonctionnalite_av_N        168 non-null    object
 65  act_social_media_N              168 non-null    object
 66  genre_N                         168 non-null    object
 67  age_N                           168 non-null    object
dtypes: float64(57), int64(1), object(10)
memory usage: 131.9+ KB

In [274]:
df.head(2)

,def_brainstorming,hbt_travail,uti_appli_brainstorming,Miro,MindMeister,XMind,Klaxoon,Lucidchart_lucidpark,Coggle,zoom_0,...,synchronisation_outil_N,task_tracking_N,outline_N,secu_donnee_N,anonymat_N,assistant_vocal_N,prix_fonctionnalite_av_N,act_social_media_N,genre_N,age_N
0,3,En groupe,Non,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,3.0,4.0,4.0,5.0,3.0,4.0,4€,Instagram,Etudiant,18-25
1,5,En groupe,Non,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,5.0,4.0,5.0,5.0,5.0,1.0,jusqu’à 15€,Instagram;Snapchat;TikTok;YouTube,Etudiant,18-25

# APPLICATION DU MAPPING ( histoire de pouvoir uniformiser les réponses )

In [339]:
# Inspection des valeurs réelles des habitudes de travail
df['hbt_travail'].value_counts(dropna=False)

hbt_travail
En groupe                     140
Individuellement              104
Individuellement;En groupe      4
Name: count, dtype: int64

In [340]:
mapping_hbt_travail = {
    'En groupe':0,
    'Individuellement':1,
    'Individuellement;En groupe' : 2
}
df['hbt_travail'] = df['hbt_travail'].map(mapping_hbt_travail)

In [316]:
# Inspection des valeurs réelles des habitudes de travail
df['hbt_travail'].value_counts(dropna=False)

hbt_travail
0    140
1    104
2      4
Name: count, dtype: int64

In [341]:
#Inspection des valeurs réelles de l'utilisation du brainstorming
df['uti_appli_brainstorming'].value_counts(dropna=False)

uti_appli_brainstorming
Non                                                   168
Non mais j’utilise mes outils de brainstorming         36
Oui                                                    25
Oui et j’utilise aussi les outils de brainstorming     19
Name: count, dtype: int64

In [342]:
mapping_uti_appli_brainstorming = {
    'Oui':1,
    'Non':0,
    'Non mais j’utilise mes outils de brainstorming': 0,
    'Oui et j’utilise aussi les outils de brainstorming':1
}
df['uti_appli_brainstorming'] = df['uti_appli_brainstorming'].map(mapping_uti_appli_brainstorming)

In [280]:
#Inspection des valeurs réelles de l'utilisation du brainstorming
df['uti_appli_brainstorming'].value_counts(dropna=False)

uti_appli_brainstorming
0    204
1     44
Name: count, dtype: int64

In [343]:
#Inspection des valeurs réelles de l'utilisation des applications de brainstorming
for col in df.columns[3:16]:
    print(f"Value counts for column: {col}")
    display(df[col].value_counts(dropna=False))
    print("\n")

Value counts for column: Miro

Miro
NaN    168
1.0     64
2.0      7
5.0      4
3.0      3
4.0      2
Name: count, dtype: int64

Value counts for column: MindMeister

MindMeister
NaN    168
1.0     63
3.0      8
5.0      4
2.0      3
4.0      2
Name: count, dtype: int64

Value counts for column: XMind

XMind
NaN    168
1.0     53
3.0     10
5.0      7
4.0      6
2.0      4
Name: count, dtype: int64

Value counts for column: Klaxoon

Klaxoon
NaN    200
1.0     20
3.0     10
2.0      7
4.0      6
5.0      5
Name: count, dtype: int64

Value counts for column: Lucidchart_lucidpark

Lucidchart_lucidpark
NaN    168
1.0     68
3.0      5
5.0      4
2.0      3
Name: count, dtype: int64

Value counts for column: Coggle

Coggle
NaN    168
1.0     67
5.0      7
4.0      2
2.0      2
3.0      2
Name: count, dtype: int64

Value counts for column: zoom_0

zoom_0
NaN    168
1.0     44
3.0     15
2.0      9
5.0      9
4.0      3
Name: count, dtype: int64

Value counts for column: Zoom

Zoom
NaN    168
5.0     22
3.0     19
2.0     17
1.0     12
4.0     10
Name: count, dtype: int64

Value counts for column: Notion_O

Notion_O
NaN    168
1.0     41
3.0     14
5.0     11
4.0      8
2.0      6
Name: count, dtype: int64

Value counts for column: Notion

Notion
NaN    168
1.0     47
3.0     10
4.0      9
5.0      9
2.0      5
Name: count, dtype: int64

Value counts for column: Figma_figjam

Figma_figjam
NaN    168
1.0     59
3.0      7
5.0      5
2.0      5
4.0      4
Name: count, dtype: int64

Value counts for column: Canva

Canva
NaN    168
5.0     26
1.0     22
3.0     11
2.0     11
4.0     10
Name: count, dtype: int64

Value counts for column: frequence_IA_O_brainsto

frequence_IA_O_brainsto
NaN    168
5.0     25
4.0     18
2.0     15
3.0     12
1.0     10
Name: count, dtype: int64

In [344]:

mapping_Miro_to_conf = {
    np.nan: 0,
    1.0 : 1,
    2.0 : 2,
    3.0 : 3,
    4.0 : 4,
    5.0 : 5
    }
for col in df.columns[3:16]:
   df[col].map(mapping_Miro_to_conf)

In [345]:


for col in df.columns[3:16]:
  df[col] = df[col].map(mapping_Miro_to_conf)

In [346]:
display(df)

,def_brainstorming,hbt_travail,uti_appli_brainstorming,Miro,MindMeister,XMind,Klaxoon,Lucidchart_lucidpark,Coggle,zoom_0,...,synchronisation_outil_N,task_tracking_N,outline_N,secu_donnee_N,anonymat_N,assistant_vocal_N,prix_fonctionnalite_av_N,act_social_media_N,genre_N,age_N
0,3,0,0,0,0,0,0,0,0,0,...,3.0,4.0,4.0,5.0,3.0,4.0,4€,Instagram,Etudiant,18-25
1,5,0,0,0,0,0,0,0,0,0,...,5.0,4.0,5.0,5.0,5.0,1.0,jusqu’à 15€,Instagram;Snapchat;TikTok;YouTube,Etudiant,18-25
2,4,0,1,2,1,1,0,1,1,2,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,2,0,0,0,0,0,0,0,0,0,...,5.0,5.0,4.0,5.0,5.0,5.0,30,Instagram;Snapchat;TikTok;LinkedIn,Etudiant,18-25
4,5,0,1,1,1,2,0,1,1,4,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
243,5,0,0,0,0,0,0,0,0,0,...,5.0,5.0,5.0,5.0,3.0,3.0,500€,LinkedIn,Cadre et profession intellectuelle supérieure,36-40
244,5,0,1,5,1,2,5,1,1,1,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
245,5,0,1,1,1,1,3,1,1,1,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
246,5,0,1,1,1,1,1,1,1,1,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
247,5,1,0,0,0,0,0,0,0,0,...,3.0,2.0,5.0,5.0,1.0,1.0,7 euros/mois,Instagram;LinkedIn;YouTube;WhatsApp,Etudiant,31-35

In [347]:
#inspection des valeurs réelles de l'utilisation de l'inréret
df['interet_appli_brainst_IA'].value_counts(dropna=False)

interet_appli_brainst_IA
NaN     168
10.0     19
7.0      13
5.0      12
8.0       9
4.0       6
9.0       5
0.0       5
6.0       4
2.0       4
3.0       3
Name: count, dtype: int64

In [348]:
mapping_interet= {
    '0.0': 0,
    '1.0':0,
    '2.0':1,
    '3.0':1,
    '4.0':2,
    '5.0':2,
    '6.0':3,
    '7.0':3,
    '8.0':4,
    '9.0':4,
    '10.0':5,

}
df['interet_appli_brainst_IA'] = df['interet_appli_brainst_IA'].map(mapping_interet)

In [354]:
#inspection des valeurs réelles de l'utilisation de l'inréret
df['interet_appli_brainst_IA'].value_counts(dropna=False)

interet_appli_brainst_IA
NaN    248
Name: count, dtype: int64

# ANALYSE DESCRIPTIVES

In [157]:
df.describe()

,def_brainstorming,Miro,MindMeister,XMind,Klaxoon,Lucidchart_lucidpark,Coggle,zoom_0,Zoom,Notion_O,...,social_media,templates_N,import_doc_N,export_doc_N,synchronisation_outil_N,task_tracking_N,outline_N,secu_donnee_N,anonymat_N,assistant_vocal_N
count,248.000000,80.000000,80.000000,80.000000,48.000000,80.00000,80.000000,80.000000,80.000000,80.000000,...,168.000000,168.000000,168.000000,168.000000,168.000000,168.000000,168.000000,168.000000,168.000000,168.00000
mean,4.225806,1.437500,1.512500,1.875000,2.354167,1.36250,1.500000,2.050000,3.162500,2.275000,...,3.892857,3.440476,4.279762,4.529762,3.875000,3.494048,4.089286,4.630952,3.839286,3.64881
std,1.216211,1.041466,1.102285,1.372192,1.406513,0.98397,1.232472,1.386189,1.427078,1.509254,...,1.089062,1.241510,1.008500,0.928108,1.239024,1.168432,1.172695,0.865573,1.254121,1.27218
min,1.000000,1.000000,1.000000,1.000000,1.000000,1.00000,1.000000,1.000000,1.000000,1.000000,...,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.00000
25%,4.000000,1.000000,1.000000,1.000000,1.000000,1.00000,1.000000,1.000000,2.000000,1.000000,...,3.000000,3.000000,4.000000,4.000000,3.000000,3.000000,3.000000,5.000000,3.000000,3.00000
50%,5.000000,1.000000,1.000000,1.000000,2.000000,1.00000,1.000000,1.000000,3.000000,1.000000,...,4.000000,3.000000,5.000000,5.000000,4.000000,4.000000,5.000000,5.000000,4.000000,4.00000
75%,5.000000,1.000000,1.000000,3.000000,3.000000,1.00000,1.000000,3.000000,5.000000,3.000000,...,5.000000,5.000000,5.000000,5.000000,5.000000,4.000000,5.000000,5.000000,5.000000,5.00000
max,5.000000,5.000000,5.000000,5.000000,5.000000,5.00000,5.000000,5.000000,5.000000,5.000000,...,5.000000,5.000000,5.000000,5.000000,5.000000,5.000000,5.000000,5.000000,5.000000,5.00000